#!/bin/bash

year=2024
day=$(date +%-d)
dir=day$day
url="https://adventofcode.com/$year/day/$day"

cargo new $dir

curl --cookie $(cat ~/.config/aoc/cookie) $url/input > $dir/input

main=$dir/src/main.rs

cat > $main <<INP
use std::fs::read_to_string;
use std::process::exit;
use std::error::Error;

fn main() -> Box<dyn Error> {
   let input = read_to_string("../input")?;

   println!("{}", res);

   Ok(())
}
INP

emacsclient -n -r $main
