#!/bin/bash

year=2024
day=$(date +%-d)
dir=day$day
url="https://adventofcode.com/$year/day/$day"

cargo new $dir

curl --cookie $(cat ~/.config/aoc/cookie) $url/input > $dir/input

main=$dir/src/main.rs

cat > $main <<INP
use std::error::Error;
use std::fs::read_to_string;

fn main() -> Result<(), Box<dyn Error>> {
   let input = read_to_string("../input")?;

   let mut res = 0;
   for line in input.lines() {
   	   
   }

   println!("{}", res);

   Ok(())
}
INP

emacsclient -n -r $main
