#!/bin/bash

year=2024
day=$(date +%-d)
dir=day$day
url="https://adventofcode.com/$year/day/$day"

cargo new $dir

curl --cookie $(cat ~/.config/aoc/cookie) $url/input > $dir/input

main=$dir/src/main.rs

cat > $main <<INP
use std::fs::read_to_string;

fn main() {
   let input = read_to_string("input").unwrap();

   println!("{}", res);
}
INP

emacsclient -n -r $main
